# Generated by Django 4.2.1 on 2023-06-01 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mandate",
            fields=[
                (
                    "mandate_id",
                    models.CharField(max_length=18, primary_key=True, serialize=False),
                ),
                ("agreed_tc", models.BooleanField()),
                ("payer_account_name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "Direct Debit Mandate",
                "verbose_name_plural": "Direct Debit Mandates",
            },
        ),
        migrations.CreateModel(
            name="DirectDebitTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("request_timestamp", models.DateTimeField()),
                ("status", models.CharField(max_length=10)),
                (
                    "mandate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recurring.mandate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Direct Debit Transaction",
                "verbose_name_plural": "Direct Debit Transactions",
            },
        ),
    ]
